apiVersion: v1
kind: ServiceAccount
metadata:
  name: paxa
  namespace: dev
secrets:
- name: paxa-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: paxa-secret
  annotations:
    kubernetes.io/service-account.name: paxa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paxa-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "delete", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: paxa-role-binding
roleRef:
  kind: Role
  name: paxa-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: paxa
  namespace: dev
