{{- range $key, $val := .Values.users }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $key }}
secrets:
- name: {{ $key }}-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}-secret
  annotations:
    kubernetes.io/service-account.name: {{ $key }}
type: kubernetes.io/service-account-token
---
{{- end }}
